START TRANSACTION;

INSERT INTO `diseases` (`Name`, `IcdCode`, `Category`) VALUES 
('Acute Myocardial Infarction', 'I21', 'Cardiovascular'),
('Atrial Fibrillation', 'I48', 'Cardiovascular'),
('Pneumonia, unspecified organism', 'J18.9', 'Respiratory'),
('Chronic Obstructive Pulmonary Disease', 'J44.9', 'Respiratory'),
('Multiple Sclerosis', 'G35', 'Neurological'),
('Alzheimers Disease', 'G30', 'Neurological'),
('Generalized Anxiety Disorder', 'F41.1', 'Mental Health'),
('Bipolar Affective Disorder', 'F31', 'Mental Health'),
('Crohns Disease', 'K50', 'Digestive'),
('Ulcerative Colitis', 'K51', 'Digestive'),
('Rheumatoid Arthritis', 'M06', 'Musculoskeletal'),
('Osteoporosis without pathological fracture', 'M81.0', 'Musculoskeletal'),
('Psoriasis Vulgaris', 'L40.0', 'Dermatological'),
('Atopic Dermatitis', 'L20', 'Dermatological'),
('Iron Deficiency Anemia', 'D50', 'Hematological'),
('Vitamin D Deficiency', 'E55.9', 'Metabolic');

INSERT INTO `medicines` (`Name`, `DosageForm`, `ActiveSubstance`) VALUES 
('Lisinopril', 'tablets', 'Lisinopril'),
('Atorvastatin', 'tablets', 'Atorvastatin Calcium'),
('Azithromycin', 'tablets', 'Azithromycin'),
('Albuterol', 'inhaler', 'Salbutamol Sulfate'),
('Lantus Solostar', 'injection', 'Insulin Glargine'),
('Zoloft', 'tablets', 'Sertraline Hydrochloride'),
('Xanax', 'tablets', 'Alprazolam'),
('Nexium', 'tablets', 'Esomeprazole'),
('Advil', 'tablets', 'Ibuprofen'),
('Tylenol Sinus', 'syrup', 'Acetaminophen + Phenylephrine'),
('Budesonide', 'inhaler', 'Budesonide'),
('Hydrochlorothiazide', 'tablets', 'Hydrochlorothiazide'),
('Metoprolol Succinate', 'tablets', 'Metoprolol'),
('Furosemide', 'injection', 'Furosemide'),
('Opatanol', 'drops', 'Olopatadine hydrochloride'),
('Diclofenac Gel', 'powder', 'Diclofenac Sodium'),
('Aspirin Cardio', 'tablets', 'Acetylsalicylic acid'),
('Clopidogrel', 'tablets', 'Clopidogrel bisulfate'),
('Symbicort Turbohaler', 'inhaler', 'Budesonide + Formoterol'),
('Spiriva HandiHaler', 'inhaler', 'Tiotropium bromide'),
('Robitussin', 'syrup', 'Dextromethorphan'),
('Lactulose Syrup', 'syrup', 'Lactulose'),
('Clexane', 'injection', 'Enoxaparin sodium'),
('Humalog', 'injection', 'Insulin Lispro'),
('Neomycin', 'drops', 'Neomycin sulfate'),
('Visine', 'drops', 'Tetryzoline hydrochloride'),
('Otrivin', 'drops', 'Xylometazoline hydrochloride'),
('Smecta', 'powder', 'Diosmectite'),
('Magnesium Citrate', 'powder', 'Magnesium ions'),
('Warfarin', 'tablets', 'Warfarin sodium'),
('Amlodipine', 'tablets', 'Amlodipine besylate'),
('Prednisolone Oral', 'syrup', 'Prednisolone'),
('Flixotide', 'inhaler', 'Fluticasone propionate'),
('Vibramycin', 'tablets', 'Doxycycline'),
('Glucophage XR', 'tablets', 'Metformin hydrochloride'),
('Tramadol', 'drops', 'Tramadol hydrochloride'),
('Bactrim', 'tablets', 'Sulfamethoxazole + Trimethoprim'),
('Epanutin', 'injection', 'Phenytoin sodium'),
('Ospamox', 'powder', 'Amoxicillin'),
('Tobrex', 'drops', 'Tobramycin'),
('Mucosolvan', 'syrup', 'Ambroxol hydrochloride'),
('Prozac', 'tablets', 'Fluoxetine'),
('Diazepam', 'tablets', 'Diazepam'),
('Imodium', 'tablets', 'Loperamide hydrochloride'),
('Mometasone', 'drops', 'Mometasone furoate'),
('Solu-Medrol', 'injection', 'Methylprednisolone');

INSERT INTO `specializations` (`Name`) VALUES 
('Internal Medicine'),
('Cardiology'),
('Pediatrics'),
('Neurology'),
('Dermatology'),
('Orthopedics'),
('Gynecology and Obstetrics'),
('General Surgery'),
('Ophthalmology'),
('Psychiatry'),
('Endocrinology'),
('Gastroenterology'),
('Oncology'),
('Urology'),
('Pulmonology'),
('Rheumatology'),
('Radiology'),
('Anesthesiology'),
('Nephrology'),
('Hematology');

COMMIT;